### ISSUE TITLE
Use XDG Base Directory for storing config

### ISSUE THREAD

**Issue by whinee** [deta/deta-cli#100]
## **Summary**
Suggestion to put deta's config at XDG base dir

## **Proposed Changes**
[XDG Base Directory](https://wiki.archlinux.org/title/XDG_Base_Directory) is a specification that defines where files should go. In this specification, it also defines where programs would put the config, called `XDG_CONFIG_HOME`, which defaults to `$HOME/.config`.

Deta could use this specification, which means that the config will be placed under `$XDG_CONFIG_HOME/deta`.

## **Rationale**
Standardization, and making `$HOME` less cluttered.

## **Reference**
- https://wiki.archlinux.org/title/XDG_Base_Directory
- https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

**Comment by faynopi** [comment]
+1

**Comment by aavshr** [comment]
sorry @whinee @faynopi  closing the issue since the repository is now being archived. You can contact us on discord or by email if you have any questions/concerns.
