### ISSUE TITLE
Cannot install deta cli in PowerShell Windows

### ISSUE THREAD

**Issue by jaydenkoh** [deta/deta-cli#39]
I tried downloading using this script; `iwr https://get.deta.dev/cli.ps1 -useb | iex`

It did not work and this is the error code:
`The term 'iwr' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spellin
g of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:4
+ iwr <<<<  https://get.deta.dev/cli.ps1 -useb | iex
    + CategoryInfo          : ObjectNotFound: (iwr:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
`

**Comment by aavshr** [comment]
`iwr` and `iex` are aliases for `Invoke-WebRequest` and `Invoke-Expression` respectively. 

Can you please try installing with 
```
Invoke-WebRequest https://get.deta.dev/cli.ps1 -useb | Invoke-Expression
```

Also, please make sure you have the latest version of powershell installed.

**Comment by aavshr** [comment]
@jaydenkoh issue is stale, closing it. Please, let us know if you still have any problems.
