### ISSUE TITLE
Update `--project` flag in man to reflect docs 

### ISSUE THREAD

**Issue by LucasZapico** [deta/deta-cli#42]
## At A Glance 

update cli man `deta new --help` `  --project string   deta project` to match docs `--project string   project to create the micro under`

**Story** 

As a user, I wanted to init a new miro under one of my other projects. From the cli I ran `deta new --help` under flags it was unclear that the `  --project string   deta project` flag was to associate the micro with a project in the data dashboard. Through the slack help channel, it was brought to my attention that in the docs the `--project string   project to create the micro under` flag is clarified further. This is therefore an oversight on my part, but sometimes tired devs like myself will try and spin up a new Deta micro. 😏  

## Expectation 

The command reference in the docs and the cli man are consistent. 

### Further Thoughts

I think it would be helpful and not overburden the docs to call out how to add micros under projects in [Getting Started - Creating Your First Micro](https://docs.deta.sh/docs/micros/getting_started#creating-your-first-micro). This is where I combed to find the answer. But, these are just my thoughts. 🤷  I'll open an issue in the docs too so the team can decide.

**Comment by abdelhai** [comment]
Hi @LucasZapico, thanks for this suggestion. Not sure how we missed your ticket.
We will update this in the next release. 🙏
