### ISSUE TITLE
Allow login from command line

### ISSUE THREAD

**Issue by Kronifer** [deta/deta-cli#43]
Deta Login is fine, but it would be much better if you could log in from the command line, like for deploying from github actions. Is it possible to add an optional flag for CLI logins? I'd be fine with implementing it.

**Comment by xeust** [comment]
Hi @Kronifer, do [access tokens](https://docs.deta.sh/docs/cli/auth#deta-access-tokens) do what you need?

A Deta user created a deploy from GitHub Actions using Access Tokens [here](https://github.com/marketplace/actions/deploy-to-deta).

**Comment by Kronifer** [comment]
This is exactly what I need! Ill close for now, but login from command line would be nice, similar to the way heroku lets you
