### ISSUE TITLE
Not allowed to change or delete some files requested

### ISSUE THREAD

**Issue by arlopezg** [deta/deta-cli#45]
Hey there,

I'm trying to deploy a micro but I'm getting the error from the title instead.

This is basically what happened:

1. `deta new --python`
2. First few deploys worked just fine
3. Changed some files, formatted, linted, etc.
4. Try to deploy again and got the error

# Prerequisites

- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

I'd like to know the specific files that can't be modified/deleted or another way to fix my deploys.

# Current Behavior

When running `deta deploy` either locally or in a CI workflow using an access token, I get the following error:

>❯ deta deploy
> Deploying...
> Error: failed to deploy: Not allowed to change or delete some files requested

## Context

* Operating System: Mac OSX 10.15.7
* SDK version:  `deta v1.1.2-beta x86_64-darwin`

## Failure Logs

None that I know of.

**Comment by arlopezg** [comment]
Nevermind, I just figured it out I think. I had moved my `main.py` to another folder and restoring it back to the root directory allowed me to deploy again.

Still, a clearer error message would be much appreciated

**Comment by Weapon-X6** [comment]
Is there a way to change the location of the main.py?

**Comment by aavshr** [comment]
@Weapon-X6 not at the moment sorry, `main.py` has to be present in the root directory of the Micro.
