### ISSUE TITLE
Deta cli doesnt show a link in headless login

### ISSUE THREAD

**Issue by rubysm** [deta/deta-cli#59]
The cli doesnt show link in login instead it shows bunch of numbers in headless mode

**Comment by abdelhai** [comment]
@rubysm `deta login` doesn't work in headless mode. Use [Access Tokens](https://docs.deta.sh/docs/cli/auth#deta-access-tokens) instead.

**Comment by rubysm** [comment]
got this error ''Error: failed to list spaces: Unauthorize''

**Comment by abdelhai** [comment]
@rubysm I believe we are in contact via Slack, so closing this issue.
