### ISSUE TITLE
I want to export / backup all Deta Base data

### ISSUE THREAD

**Issue by Neos21** [deta/deta-cli#62]
I want to export or backup all data of Deta Base.
I want the data to be output as a JSON file.
But, `fetch` API limits 1MB. ([Ref](https://docs.deta.sh/docs/base/sdk#fetch))
How to export all data that over 1MB?

**Comment by abdelhai** [comment]
Hi @Neos21, the limit of 1MB is only for one page, you can keep fetching next pages by passing the `last` parameter/option. Make sure to use the our >1.0.0 version of the SDK and the docs.
