### ISSUE TITLE
I could not run data-cli in linux 

### ISSUE THREAD

**Issue by pt67** [deta/deta-cli#82]
I run the following command on my terminal and after successful install, i could not found anything by hitting deta --help.
Would you please suggest me how to do that?

curl -fsSL https://get.deta.dev/cli.sh | sh

**Comment by aavshr** [comment]
hello, if the command `deta` does not run in a new terminal you will have to manually update the `PATH` to include the `$HOME/.deta/bin` (`$HOME` here is your home directory that's local to your system) directory where the cli is installed.
