### ISSUE TITLE
feat: Support for connecting existing directory to an existing Micro

### ISSUE THREAD

**Issue by ajhalili2006** [deta/deta-cli#86]
## Suggestion

Have some sort of `connect` command in the CLI to seamlessly connect existing directory to an existing Micro without pain.

## Workarounds

Currently, the only workaround is copy the contents of `$PWD/.deta/prog_info` file to the target machine or even set it as an secret in CI settings and do some "echo $DETA_PROG_INFO > .deta/prog_info`.

**Comment by abdelhai** [comment]
adding this to our next release todo list
