### ISSUE TITLE
Feature Request: clone/get `.deta` folder only

### ISSUE THREAD

**Issue by ArnabXD** [deta/deta-cli#95]
People who use git to store/backup/track their codebase can have some additional files for development. But they aren't pushed to deta micro using `.detaignore`. In this case, I clone the project from deta, clone the main codebase from git services and then copy the `.deta` folder to my git cloned codebase. It would be nicer if I could just get the `.deta` folder to identify the project to deta.

**Comment by abdelhai** [comment]
thanks for the feedback. we will make sure to support this in our next cli release. cc @rohanshiva

**Comment by aavshr** [comment]
sorry @ArnabXD  closing the issue since the repository is now being archived. You can contact us on discord or by email if you have any questions/concerns.
