### ISSUE TITLE
[ future request ] uninstal.sh

### ISSUE THREAD

**Issue by chiboreache** [deta/deta-cli#97]
would be nice to have..

**Comment by abdelhai** [comment]
never

**Comment by chiboreache** [comment]
lol why?

**Comment by abdelhai** [comment]
jk. we will consider it for our next release. thanks!

**Comment by aavshr** [comment]
sorry @chiboreache closing the issue since the repository is now being archived. You can contact us on discord or by email if you have any questions/concerns.
