### ISSUE TITLE
Add command "deta deploy --force"

### ISSUE THREAD

**Issue by cofob** [deta/deta-cli#98]
Add a command that will ignore `.deta/state` and load all files, while writing new hashes to `.deta/state`. For example `deta deploy -f/--force`.

**Comment by abdelhai** [comment]
good idea! cc @rohanshiva @aavshr

**Comment by aavshr** [comment]
sorry @cofob closing the issue since the repository is now being archived. You can contact us on discord or by email if you have any questions/concerns.
